<!DOCTYPE html>
<html lang="en">

<link rel="stylesheet" href="start_screen.css">

<head>
    <meta charset="UTF-8">
    <title>x Quiz</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<form action="/QuizController.php" method="POST">
<div class="quiz-container">
    <h1>x Quiz</h1>
    <p>Are you ready to test your knowledge?</p>
    <button type="submit" class="quiz-button">Start the Quiz</button>
</div>
</form>
</body>
</html>
